import blocks.py
import color_guessing.py
import colox.py
import dice.py
import hangman.py
import master_mid.py
import number_details.py
import number_guessing.py 
import rock-paper-scissors.py
import snake_game.py
import snake_ladder.py 
import star.py
import tick_cross.py
import tick_cross_gui.py
import twenty-one.py
import typing_speed.py
