from .Calculator import time
from .Calculator import ASCII
from .Calculator import Mortgage
from .Calculator import Quadratic_Equation
from .Calculator import bmi
from .Calculator import conject
from .Calculator import grade
from .Calculator import graph
from .Calculator import int_diff
from .Calculator import mega_calculator
from .Calculator import number_base
from .Calculator import roman_number
from .Calculator import sequence
from .Calculator import special_relativity_calculator
from .Calculator import stock
from .Calculator import sudoku
from .Calculator import time_calculator

from .GUI import A_basic_gui_calculator
from .GUI import Form
from .GUI import Pikachu
from .GUI import Quiz
from .GUI import clender
from .GUI import clock
from .GUI import doraemon
from .GUI import file_explorer
from .GUI import graphics
from .GUI import happy_birth_day
from .GUI import notepad
from .GUI import paint
from .GUI import rainbow
from .GUI import search_applications
from .GUI import snake_ladder
from .GUI import spelling
from .GUI import spinner
from .GUI import tick_cross
from .GUI import todo
from .GUI import youtube_download

from .Game import blocks
from .Game import color_guessing
from .Game import colox
from .Game import dice
from .Game import hangman
from .Game import master_mid
from .Game import number_details
from .Game import number_guessing
from .Game import rock_paper_scisors
from .Game import snake_game
from .Game import snake_ladder
from .Game import star
from .Game import tick_cross
from .Game import tick_cross_gui
from .Game import twenty_one
from .Game import typing_speed

from .Utilities import brithday
from .Utilities import broswer
from .Utilities import btc
from .Utilities import connectivity
from .Utilities import count_down
from .Utilities import github
from .Utilities import google
from .Utilities import insta
from .Utilities import network
from .Utilities import password
from .Utilities import password_hash
from .Utilities import password_manager
from .Utilities import passwrd_generator
from .Utilities import secert_code
from .Utilities import short_form
from .Utilities import transfer
from .Utilities import url
from .Utilities import whatsapp_spam
from .Utilities import word_count

from .machine_learning import brightness_controllor
from .machine_learning import camera
from .machine_learning import crypto_prices
from .machine_learning import eye_blink
from .machine_learning import gold_price
from .machine_learning import lang_dect
from .machine_learning import sentiments
from .machine_learning import sketch
from .machine_learning import spam_dect
from .machine_learning import text_to_speech
