import A_basic_gui_calculator
import Form
import Pikachu
import Quiz
import clender
import clock
import doraemon
import file_explorer
import graphics
import happy_birth_day
import notepad
import paint
import rainbow
import search_applications
import snake_ladder
import spelling
import spinner
import tick_cross
import todo
import youtube_download
