import A_basic_gui_calculator.py
import Form.py
import Pikachu.py
import Quiz.py
import clender.py
import clock.py
import doraemon.py
import file_explorer.py
import graphics.py
import happy_birth_day.py
import notepad.py
import paint.py
import rainbow.py
import search_applications.py
import snake_ladder.py
import spelling.py
import spinner.py
import tick_cross.py
import todo.py
import youtube_download.py
