#This code is made by MRayan Asim
#The turtle is a built-in module of the python but you can install it by:
#pip install Pythonturtle
import turtle

class Cartoon:
    def __init__(self):
        self.screen = turtle.Screen()
        self.screen.setup(1800, 800)
        self.screen.title('Cartoon')
        self.t = turtle.Turtle()
        self.t.pensize(3)
        self.t.speed(9)
        self.t.ondrag(self.move_turtle)

    def move_turtle(self, x, y):
        self.t.penup()
        self.t.setpos(x, y)
        self.t.pendown()

    def draw_circle(self, x, y, radius, color):
        self.t.penup()
        self.t.goto(x, y)
        self.t.pendown()
        self.t.fillcolor(color)
        self.t.begin_fill()
        self.t.circle(radius)
        self.t.end_fill()

    def draw_eye(self, x, y, inner_radius, outer_radius):
        self.draw_circle(x, y, outer_radius, '#333333')
        self.draw_circle(x, y + 10, inner_radius, '#000000')
        self.draw_circle(x + 6, y + 22, inner_radius, '#ffffff')

    def draw_mouth(self, x, y):
        self.t.penup()
        self.t.goto(x, y)
        self.t.pendown()

        self.t.fillcolor('#88141D')
        self.t.begin_fill()

        l1, l2 = [], []
        self.t.seth(190)
        a = 0.7
        for i in range(28):
            a += 0.1
            self.t.right(3)
            self.t.fd(a)
            l1.append(self.t.position())

        self.t.penup()
        self.t.goto(x, y)
        self.t.pendown()

        self.t.seth(10)
        a = 0.7
        for i in range(28):
            a += 0.1
            self.t.left(3)
            self.t.fd(a)
            l2.append(self.t.position())

        self.t.seth(10)
        self.t.circle(50, 15)
        self.t.left(180)
        self.t.circle(-50, 15)
        self.t.circle(-50, 40)
        self.t.seth(233)
        self.t.circle(-50, 55)
        self.t.left(180)
        self.t.circle(50, 12.1)
        self.t.end_fill()

        self.t.penup()
        self.t.goto(17, 54)
        self.t.pendown()
        self.t.fillcolor('#DD716F')
        self.t.begin_fill()
        self.t.seth(145)
        self.t.circle(40, 86)
        self.t.penup()
        for pos in reversed(l1[:20]):
            self.t.goto(pos[0], pos[1] + 1.5)
        for pos in l2[:20]:
            self.t.goto(pos[0], pos[1] + 1.5)
        self.t.pendown()
        self.t.end_fill()

        self.t.penup()
        self.t.goto(-17, 94)
        self.t.pendown()
        self.t.seth(8)
        self.t.fd(4)
        self.t.back(8)

    def draw_cheek(self, x, y):
        self.t.tracer(False)
        self.t.penup()
        self.t.goto(x, y)
        self.t.pendown()
        self.t.seth(300)
        self.t.fillcolor('#DD4D28')
        self.t.begin_fill()
        a = 2.3
        for i in range(120):
            if 0 <= i < 30 or 60 <= i < 90:
                a -= 0.05
                self.t.lt(3)
                self.t.fd(a)
            else:
                a += 0.05
                self.t.lt(3)
                self.t.fd(a)
        self.t.end_fill()
        self.t.tracer(True)

    def draw_ear(self, x, y):
        self.t.penup()
        self.t.goto(x, y)
        self.t.pendown()
        self.t.fillcolor('#000000')
        self.t.begin_fill()
        self.t.seth(330)
        self.t.circle(100, 35)
        self.t.seth(219)
        self.t.circle(-300, 19)
        self.t.seth(110)
        self.t.circle(-30, 50)
        self.t.circle(-300, 10)
        self.t.end_fill()

    def draw_hair(self, x, y):
        self.t.penup()
        self.t.goto(x, y)
        self.t.pendown()

        self.t.fillcolor('#F6D02F')
        self.t.begin_fill()

        self.t.circle(130, 40)
        self.t.circle(100, 105)
        self.t.left(180)
        self.t.circle(-100, 5)

        self.t.seth(20)
        self.t.circle(300, 30)
        self.t.circle(30, 50)
        self.t.seth(190)
        self.t.circle(300, 36)

        self.t.seth(150)
        self.t.circle(150, 70)

        self.t.seth(200)
        self.t.circle(300, 40)
        self.t.circle(30, 50)
        self.t.seth(20)
        self.t.circle(300, 35)

        self.t.seth(240)
        self.t.circle(105, 95)
        self.t.left(180)
        self.t.circle(-105, 5)

        self.t.seth(210)
        self.t.circle(500, 18)
        self.t.seth(200)
        self.t.fd(10)
        self.t.seth(280)
        self.t.fd(7)
        self.t.seth(210)
        self.t.fd(10)
        self.t.seth(300)
        self.t.circle(10, 80)
        self.t.seth(220)
        self.t.fd(10)
        self.t.seth(300)
        self.t.circle(10, 80)
        self.t.seth(240)
        self.t.fd(12)
        self.t.seth(0)
        self.t.fd(13)
        self.t.seth(240)
        self.t.circle(10, 70)
        self.t.seth(10)
        self.t.circle(10, 70)
        self.t.seth(10)
        self.t.circle(300, 18)

        self.t.seth(75)
        self.t.circle(500, 8)
        self.t.left(180)
        self.t.circle(-500, 15)
        self.t.seth(250)
        self.t.circle(100, 65)

        self.t.seth(320)
        self.t.circle(100, 5)
        self.t.left(180)
        self.t.circle(-100, 5)
        self.t.seth(220)
        self.t.circle(200, 20)
        self.t.circle(20, 70)

        self.t.seth(60)
        self.t.circle(-100, 20)
        self.t.left(180)
        self.t.circle(100, 20)
        self.t.seth(300)
        self.t.circle(10, 70)

        self.t.seth(60)
        self.t.circle(-100, 20)
        self.t.left(180)
        self.t.circle(100, 20)
        self.t.seth(10)
        self.t.circle(100, 60)

        self.t.seth(180)
        self.t.circle(-100, 10)
        self.t.left(180)
        self.t.circle(100, 10)
        self.t.seth(5)
        self.t.circle(100, 10)
        self.t.circle(-100, 40)
        self.t.circle(100, 35)
        self.t.left(180)
        self.t.circle(-100, 10)

        self.t.seth(290)
        self.t.circle(100, 55)
        self.t.circle(10, 50)

        self.t.seth(120)
        self.t.circle(100, 20)
        self.t.left(180)
        self.t.circle(-100, 20)

        self.t.seth(0)
        self.t.circle(10, 50)

        self.t.seth(110)
        self.t.circle(100, 20)
        self.t.left(180)
        self.t.circle(-100, 20)

        self.t.seth(30)
        self.t.circle(20, 50)

        self.t.seth(100)
        self.t.circle(100, 40)

        self.t.seth(200)
        self.t.circle(-100, 5)
        self.t.left(180)
        self.t.circle(100, 5)
        self.t.left(30)
        self.t.fd(10)
        self.t.circle(-5, 160)
        self.t.fd(10)

        self.t.seth(-90)
        self.t.fd(3)
        self.t.circle(-4, 180)
        self.t.fd(3)
        self.t.seth(-90)
        self.t.fd(3)
        self.t.circle(-4, 180)
        self.t.fd(3)

        self.t.fillcolor('#228B22')
        self.t.seth(40)
        self.t.fd(200)
        self.t.seth(-80)
        self.t.fd(150)
        self.t.seth(210)
        self.t.fd(150)
        self.t.left(90)
        self.t.fd(100)
        self.t.right(95)
        self.t.fd(100)
        self.t.left(110)
        self.t.fd(70)
        self.t.right(110)
        self.t.fd(80)
        self.t.left(110)
        self.t.fd(30)
        self.t.right(110)
        self.t.fd(32)

        self.t.right(106)
        self.t.circle(100, 25)
        self.t.right(15)
        self.t.circle(-300, 2)

        self.t.seth(30)
        self.t.fd(40)
        self.t.left(100)
        self.t.fd(70)
        self.t.right(100)
        self.t.fd(80)
        self.t.left(100)
        self.t.fd(46)
        self.t.seth(66)
        self.t.circle(200, 38)
        self.t.right(10)
        self.t.fd(10)
        self.t.end_fill()

        self.t.penup()
        self.t.goto(126.82, -156.84)
        self.t.pendown()
        self.t.begin_fill()
        self.t.seth(30)
        self.t.fd(40)
        self.t.left(100)
        self.t.fd(40)
        self.t.pencolor('#923e24')
        self.t.seth(-30)
        self.t.fd(30)
        self.t.left(140)
        self.t.fd(20)
        self.t.right(150)
        self.t.fd(20)
        self.t.left(150)
        self.t.fd(20)
        self.t.right(150)
        self.t.fd(20)
        self.t.left(130)
        self.t.fd(18)
        self.t.pencolor('#000000')
        self.t.seth(-45)
        self.t.fd(67)
        self.t.right(110)
        self.t.fd(80)
        self.t.left(110)
        self.t.fd(30)
        self.t.right(110)
        self.t.fd(32)
        self.t.right(106)
        self.t.circle(100, 25)
        self.t.right(15)
        self.t.circle(-300, 2)
        self.t.end_fill()

        self.t.penup()
        self.t.goto(-58, 270)
        self.t.pendown()
        self.t.fillcolor('#444444')
        self.t.begin_fill()
        self.t.left(180)
        self.t.circle(80, 197)
        self.t.left(58)
        self.t.circle(200, 45)
        self.t.end_fill()

        self.t.penup()
        self.t.goto(-30, 280)
        self.t.pendown()
        self.t.fillcolor('#228B22')
        self.t.begin_fill()
        self.t.seth(100)
        self.t.circle(30, 180)
        self.t.seth(190)
        self.t.fd(15)
        self.t.seth(100)
        self.t.circle(-45, 180)
        self.t.right(90)
        self.t.fd(15)
        self.t.end_fill()

        self.t.penup()
        self.t.goto(-168.47, 185.52)
        self.t.pendown()
        self.t.begin_fill()
        self.t.seth(36)
        self.t.circle(-270, 54)
        self.t.left(180)
        self.t.circle(270, 27)
        self.t.circle(-80, 98)
        self.t.end_fill()

        self.t.penup()
        self.t.goto(-126, 32)
        self.t.pendown()
        self.t.seth(300)
        self.t.fillcolor('#DD4D28')
        self.t.begin_fill()
        a = 2.3
        for i in range(120):
            if 0 <= i < 30 or 60 <= i < 90:
                a -= 0.05
                self.t.lt(3)
                self.t.fd(a)
            else:
                a += 0.05
                self.t.lt(3)
                self.t.fd(a)
        self.t.end_fill()

    def draw_jiu(self):
        self.draw_mouth(-5, 25)
        self.draw_cheek(-126, 32)
        self.draw_cheek(107, 63)
        self.draw_ear(-250, 100)
        self.draw_ear(140, 270)
        self.draw_eye(-85, 90, 10, 22)
        self.draw_eye(50, 110, 10, 22)

        self.t.hideturtle()

    def draw_topi(self):
        self.t.pencolor('#000000')
        self.draw_hair(130, 125)
        self.t.penup()
        self.t.goto(-134.07, 147.81)
        self.t.pendown()
        self.t.seth(36)
        self.t.circle(-270, 54)
        self.t.left(180)
        self.t.circle(270, 27)
        self.t.circle(-80, 98)
        self.t.penup()
        self.t.goto(-126.82, 156.84)
        self.t.pendown()
        self.t.fillcolor('#F6D02F')
        self.t.begin_fill()
        self.t.circle(130, 40)
        self.t.circle(100, 105)
        self.t.left(180)
        self.t.circle(-100, 5)
        self.t.seth(20)
        self.t.circle(300, 30)
        self.t.circle(30, 50)
        self.t.seth(190)
        self.t.circle(300, 36)
        self.t.seth(150)
        self.t.circle(150, 70)
        self.t.seth(200)
        self.t.circle(300, 40)
        self.t.circle(30, 50)
        self.t.seth(20)
        self.t.circle(300, 35)
        self.t.seth(240)
        self.t.circle(105, 95)
        self.t.left(180)
        self.t.circle(-105, 5)
        self.t.seth(210)
        self.t.circle(500, 18)
        self.t.seth(200)
        self.t.fd(10)
        self.t.seth(280)
        self.t.fd(7)
        self.t.seth(210)
        self.t.fd(10)
        self.t.seth(300)
        self.t.circle(10, 80)
        self.t.seth(220)
        self.t.fd(10)
        self.t.seth(300)
        self.t.circle(10, 80)
        self.t.seth(240)
        self.t.fd(12)
        self.t.seth(0)
        self.t.fd(13)
        self.t.seth(240)
        self.t.circle(10, 70)
        self.t.seth(10)
        self.t.circle(10, 70)
        self.t.seth(10)
        self.t.circle(300, 18)
        self.t.seth(75)
        self.t.circle(500, 8)
        self.t.left(180)
        self.t.circle(-500, 15)
        self.t.seth(250)
        self.t.circle(100, 65)
        self.t.seth(320)
        self.t.circle(100, 5)
        self.t.left(180)
        self.t.circle(-100, 5)
        self.t.seth(220)
        self.t.circle(200, 20)
        self.t.circle(20, 70)
        self.t.seth(60)
        self.t.circle(-100, 20)
        self.t.left(180)
        self.t.circle(100, 20)
        self.t.seth(300)
        self.t.circle(10, 70)
        self.t.seth(60)
        self.t.circle(-100, 20)
        self.t.left(180)
        self.t.circle(100, 20)
        self.t.seth(10)
        self.t.circle(100, 60)
        self.t.seth(180)
        self.t.circle(-100, 10)
        self.t.left(180)
        self.t.circle(100, 10)
        self.t.seth(5)
        self.t.circle(100, 10)
        self.t.circle(-100, 40)
        self.t.circle(100, 35)
        self.t.left(180)
        self.t.circle(-100, 10)
        self.t.seth(290)
        self.t.circle(100, 55)
        self.t.circle(10, 50)
        self.t.seth(120)
        self.t.circle(100, 20)
        self.t.left(180)
        self.t.circle(-100, 20)
        self.t.seth(0)
        self.t.circle(10, 50)
        self.t.seth(110)
        self.t.circle(100, 20)
        self.t.left(180)
        self.t.circle(-100, 20)
        self.t.seth(30)
        self.t.circle(20, 50)
        self.t.seth(100)
        self.t.circle(100, 40)
        self.t.seth(200)
        self.t.circle(-100, 5)
        self.t.left(180)
        self.t.circle(100, 5)
        self.t.left(30)
        self.t.fd(10)
        self.t.circle(-5, 160)
        self.t.fd(10)
        self.t.seth(-90)
        self.t.fd(3)
        self.t.circle(-4, 180)
        self.t.fd(3)
        self.t.seth(-90)
        self.t.fd(3)
        self.t.circle(-4, 180)
        self.t.fd(3)
        self.t.end_fill()

        self.t.penup()
        self.t.goto(168.47, 185.52)
        self.t.pendown()
        self.t.begin_fill()
        self.t.seth(40)
        self.t.fd(200)
        self.t.seth(-80)
        self.t.fd(150)
        self.t.seth(210)
        self.t.fd(150)
        self.t.left(90)
        self.t.fd(100)
        self.t.right(95)
        self.t.fd(100)
        self.t.left(110)
        self.t.fd(70)
        self.t.right(110)
        self.t.fd(80)
        self.t.left(110)
        self.t.fd(30)
        self.t.right(110)
        self.t.fd(32)
        self.t.right(106)
        self.t.circle(100, 25)
        self.t.right(15)
        self.t.circle(-300, 2)
        self.t.seth(30)
        self.t.fd(40)
        self.t.left(100)
        self.t.fd(70)
        self.t.right(100)
        self.t.fd(80)
        self.t.left(100)
        self.t.fd(46)
        self.t.seth(66)
        self.t.circle(200, 38)
        self.t.right(10)
        self.t.fd(10)
        self.t.end_fill()

        self.t.penup()
        self.t.goto(126.82, -156.84)
        self.t.pendown()
        self.t.seth(30)
        self.t.fd(40)
        self.t.left(100)
        self.t.fd(40)
        self.t.pencolor('#923e24')
        self.t.seth(-30)
        self.t.fd(30)
        self.t.left(140)
        self.t.fd(20)
        self.t.right(150)
        self.t.fd(20)
        self.t.left(150)
        self.t.fd(20)
        self.t.right(150)
        self.t.fd(20)
        self.t.left(130)
        self.t.fd(18)
        self.t.pencolor('#000000')
        self.t.seth(-45)
        self.t.fd(67)
        self.t.right(110)
        self.t.fd(80)
        self.t.left(110)
        self.t.fd(30)
        self.t.right(110)
        self.t.fd(32)
        self.t.right(106)
        self.t.circle(100, 25)
        self.t.right(15)
        self.t.circle(-300, 2)
        self.t.end_fill()

        self.t.penup()
        self.t.goto(-58, 270)
        self.t.pendown()
        self.t.fillcolor('#444444')
        self.t.begin_fill()
        self.t.left(180)
        self.t.circle(80, 197)
        self.t.left(58)
        self.t.circle(200, 45)
        self.t.end_fill()

        self.t.penup()
        self.t.goto(-30, 280)
        self.t.pendown()
        self.t.fillcolor('#228B22')
        self.t.begin_fill()
        self.t.seth(100)
        self.t.circle(30, 180)
        self.t.seth(190)
        self.t.fd(15)
        self.t.seth(100)
        self.t.circle(-45, 180)
        self.t.right(90)
        self.t.fd(15)
        self.t.end_fill()

        self.t.penup()
        self.t.goto(-168.47, 185.52)
        self.t.pendown()
        self.t.begin_fill()
        self.t.seth(36)
        self.t.circle(-270, 54)
        self.t.left(180)
        self.t.circle(270, 27)
        self.t.circle(-80, 98)
        self.t.end_fill()

        self.t.penup()
        self.t.goto(-126, 32)
        self.t.pendown()
        self.t.seth(300)
        self.t.fillcolor('#DD4D28')
        self.t.begin_fill()
        a = 2.3
        for i in range(120):
            if 0 <= i < 30 or 60 <= i < 90:
                a -= 0.05
                self.t.lt(3)
                self.t.fd(a)
            else:
                a += 0.05
                self.t.lt(3)
                self.t.fd(a)
        self.t.end_fill()

        self.draw_ear(-250, 100)
        self.draw_ear(140, 270)

        self.t.hideturtle()

    def main(self):
        self.t.speed(0)
        self.t.pensize(3)

        self.draw_jiu()
        self.draw_topi()

        self.screen.mainloop()

if __name__ == "__main__":
    cartoon = Cartoon()
    cartoon.main()

