name: Check Code Lines

on:
  push:
    branches:
      - main

jobs:
  check_code_lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Count Python lines
        id: count_python_lines
        run: |
          python_lines=$(find . -name '*.py' -print0 | xargs -0 cat 2>/dev/null | wc -l)
          python_files=$(find . -name '*.py' -print0 | tr -cd '\0' | wc -c)
          echo "python_lines=$python_lines" >> $GITHUB_OUTPUT
          echo "python_files=$python_files" >> $GITHUB_OUTPUT

      - name: Count TXT lines
        id: count_txt_lines
        run: |
          txt_lines=$(find . -name '*.txt' -print0 | xargs -0 cat 2>/dev/null | wc -l)
          txt_files=$(find . -name '*.txt' -print0 | tr -cd '\0' | wc -c)
          echo "txt_lines=$txt_lines" >> $GITHUB_OUTPUT
          echo "txt_files=$txt_files" >> $GITHUB_OUTPUT

      - name: Count MD lines
        id: count_md_lines
        run: |
          md_lines=$(find . -name '*.md' -print0 | xargs -0 cat 2>/dev/null | wc -l)
          md_files=$(find . -name '*.md' -print0 | tr -cd '\0' | wc -c)
          echo "md_lines=$md_lines" >> $GITHUB_OUTPUT
          echo "md_files=$md_files" >> $GITHUB_OUTPUT

      - name: Display results
        run: |
          echo "Total lines of Python code: ${{ steps.count_python_lines.outputs.python_lines }}"
          echo "Total lines of Python files: ${{ steps.count_python_lines.outputs.python_files }}"
          echo "Total lines of TXT code: ${{ steps.count_txt_lines.outputs.txt_lines }}"
          echo "Total lines of TXT files: ${{ steps.count_txt_lines.outputs.txt_files }}"
          echo "Total lines of MD code: ${{ steps.count_md_lines.outputs.md_lines }}"
          echo "Total lines of MD files: ${{ steps.count_md_lines.outputs.md_files }}"
